dependencies:
  - python=3.7.7
  - r-base=3.5.3
  - pip
  - pip:
    - plotly
    - pandas
    - matplotlib
    - scikitlearn
    - numpy
    - ipykernel
    - bash_kernel
  - r-dpylyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - stringr
